resources:
  repositories:
    - repository: templates
      type: github
      name: stratsys/Pipeline.Templates
      ref: master
      endpoint: "GitHub Stratsys"

variables:
  - name: RELEASE_BRANCH
    value: $(Build.SourceBranchName)
  - name: COMPLETE_RELEASE_BRANCH
    value: $(Build.SourceBranch)
  - name: GIT_COMMIT_SHA
    value: $(Build.SourceVersion)
  - group: "Github-Playbook"
  - group: "Azure Key Vault"

trigger:
  - master

pool: "Linux-docker"

steps:
- template: pipelines.yml@templates
